<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>Exe</OutputType>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<UseWPF>true</UseWPF>
		<PlatformTarget>x86</PlatformTarget>
		<OutputPath>$(SolutionDir)bin\$(Configuration)\</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="ItemTarget\**\*.cs" />
		<ProjectReference Include="..\QHackLib\QHackLib.csproj" />
		<ProjectReference Include="..\QTRHacker.Core\QTRHacker.Core.csproj" />
		<ProjectReference Include="..\QTRHacker\QTRHacker.csproj" />
		<ProjectReference Include="..\QHackCLR.TestTarget\QHackCLR.TestTarget.csproj" ReferenceOutputAssembly="false" SkipGetTargetFrameworkProperties="true" />
	</ItemGroup>

</Project>
