using System;
using System.Runtime.InteropServices;
using QHackCLR.Dac.COM;
using QHackCLR.Dac.Utils;
namespace QHackCLR.Dac.Interfaces
{
	[Flags]
	public enum CLRDataAddressType : uint
	{
		CLRDATA_ADDRESS_UNRECOGNIZED,
		CLRDATA_ADDRESS_MANAGED_METHOD,
		CLRDATA_ADDRESS_RUNTIME_MANAGED_CODE,
		CLRDATA_ADDRESS_RUNTIME_UNMANAGED_CODE,
		CLRDATA_ADDRESS_GC_DATA,
		CLRDATA_ADDRESS_RUNTIME_MANAGED_STUB,
		CLRDATA_ADDRESS_RUNTIME_UNMANAGED_STUB,
	}
}
