using System;
using System.Runtime.InteropServices;
using QHackCLR.Dac.COM;
using QHackCLR.Dac.Utils;
namespace QHackCLR.Dac.Interfaces
{
	[Flags]
	public enum CLRDataDetailedFrameType : uint
	{
		CLRDATA_DETFRAME_UNRECOGNIZED,
		CLRDATA_DETFRAME_UNKNOWN_STUB,
		CLRDATA_DETFRAME_CLASS_INIT,
		CLRDATA_DETFRAME_EXCEPTION_FILTER,
		CLRDATA_DETFRAME_SECURITY,
		CLRDATA_DETFRAME_CONTEXT_POLICY,
		CLRDATA_DETFRAME_INTERCEPTION,
		CLRDATA_DETFRAME_PROCESS_START,
		CLRDATA_DETFRAME_THREAD_START,
		CLRDATA_DETFRAME_TRANSITION_TO_MANAGED,
		CLRDATA_DETFRAME_TRANSITION_TO_UNMANAGED,
		CLRDATA_DETFRAME_COM_INTEROP_STUB,
		CLRDATA_DETFRAME_DEBUGGER_EVAL,
		CLRDATA_DETFRAME_CONTEXT_SWITCH,
		CLRDATA_DETFRAME_FUNC_EVAL,
		CLRDATA_DETFRAME_FINALLY,
	}
}
